#!/bin/bash
set -Eeuo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_SOURCE="${CRF_AUDIT_SOURCE:-$SCRIPT_DIR/fleet-audit.sh}"
BOOT_CONFIG_ROOT="${CRF_BOOT_CONFIG_ROOT:-/boot/config}"
PLUGIN=ci-runner-farm
PLUGIN_CONFIG_DIR="${CRF_PLUGIN_CONFIG_DIR:-$BOOT_CONFIG_ROOT/plugins/$PLUGIN}"
PLUGIN_PLG="${CRF_PLUGIN_PLG:-$PLUGIN_CONFIG_DIR.plg}"
AUDIT_INSTALL_PATH="${CRF_AUDIT_INSTALL_PATH:-$PLUGIN_CONFIG_DIR/fleet-audit.sh}"
AUDIT_CONFIG="${CRF_AUDIT_CONFIG:-$PLUGIN_CONFIG_DIR/fleet-audit.env}"
AUDIT_LOG_ROOT="${CRF_AUDIT_LOG_ROOT:-/mnt/user/logs/ci-runner-farm-audit}"
USER_SCRIPTS_ROOT="${CRF_USER_SCRIPTS_ROOT:-$BOOT_CONFIG_ROOT/plugins/user.scripts}"
USER_SCRIPT_DIR="${CRF_USER_SCRIPT_DIR:-$USER_SCRIPTS_ROOT/scripts/ci-runner-farm-audit}"
USER_SCRIPT_PATH="$USER_SCRIPT_DIR/script"
SCHEDULE_JSON="${CRF_SCHEDULE_JSON:-$USER_SCRIPTS_ROOT/schedule.json}"
CUSTOM_CRON="${CRF_CUSTOM_CRON:-$USER_SCRIPTS_ROOT/customSchedule.cron}"
SCHEDULE="${CRF_AUDIT_SCHEDULE:-30 6 * * *}"
SCHEDULE_ID="${CRF_AUDIT_SCHEDULE_ID:-scheduleci-runner-farm-audit}"
UPDATE_CRON="${CRF_UPDATE_CRON:-1}"
RUN_AUDIT="${CRF_INSTALL_RUN_AUDIT:-0}"

[ -f "$AUDIT_SOURCE" ] && [ ! -L "$AUDIT_SOURCE" ] ||
  { echo "fleet audit source is unavailable: $AUDIT_SOURCE" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }
[[ "$SCHEDULE" =~ ^[^[:cntrl:]]{1,64}$ ]] ||
  { echo "invalid audit schedule" >&2; exit 1; }

mkdir -p "$PLUGIN_CONFIG_DIR" "$USER_SCRIPT_DIR" "$(dirname "$SCHEDULE_JSON")" "$AUDIT_LOG_ROOT"
chmod 0775 "$AUDIT_LOG_ROOT" 2>/dev/null || true

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
backup_dir="$PLUGIN_CONFIG_DIR/audit-schedule-backups/$stamp"
mkdir -p "$backup_dir"
[ ! -e "$SCHEDULE_JSON" ] || cp -a "$SCHEDULE_JSON" "$backup_dir/schedule.json"
[ ! -e "$CUSTOM_CRON" ] || cp -a "$CUSTOM_CRON" "$backup_dir/customSchedule.cron"

install -m 0755 "$AUDIT_SOURCE" "$AUDIT_INSTALL_PATH"

[ -f "$PLUGIN_PLG" ] || { echo "plugin registration is unavailable: $PLUGIN_PLG" >&2; exit 1; }
plugin_version="$(sed -n 's/^<!ENTITY pluginVersion[[:space:]]*"\([^"]*\)">$/\1/p' "$PLUGIN_PLG")"
package_name="$(sed -n 's/^<!ENTITY packageName[[:space:]]*"\([^"]*\)">$/\1/p' "$PLUGIN_PLG")"
package_path="$PLUGIN_CONFIG_DIR/$package_name"
[ -n "$plugin_version" ] && [ -n "$package_name" ] && [ -f "$package_path" ] ||
  { echo "could not resolve the installed plugin package" >&2; exit 1; }
package_hash="$(sha256sum "$package_path" | awk '{print $1}')"
[[ "$package_hash" =~ ^[0-9a-f]{64}$ ]] ||
  { echo "invalid plugin package hash" >&2; exit 1; }

config_tmp="$AUDIT_CONFIG.tmp.$$"
cat > "$config_tmp" <<EOF
# Installed fleet audit identity. Regenerated by install-fleet-audit.sh.
CRF_EXPECTED_PLUGIN_VERSION='$plugin_version'
CRF_EXPECTED_PLUGIN_PACKAGE_SHA256='$package_hash'
EOF
chmod 0600 "$config_tmp"
mv "$config_tmp" "$AUDIT_CONFIG"

wrapper_tmp="$USER_SCRIPT_PATH.tmp.$$"
cat > "$wrapper_tmp" <<EOF
#!/bin/bash
exec '$AUDIT_INSTALL_PATH'
EOF
chmod 0755 "$wrapper_tmp"
mv "$wrapper_tmp" "$USER_SCRIPT_PATH"

if [ ! -e "$SCHEDULE_JSON" ]; then
  printf '{}\n' > "$SCHEDULE_JSON"
fi
jq -e 'type == "object"' "$SCHEDULE_JSON" >/dev/null ||
  { echo "invalid User Scripts schedule JSON" >&2; exit 1; }
schedule_tmp="$SCHEDULE_JSON.tmp.$$"
jq --arg script "$USER_SCRIPT_PATH" --arg schedule "$SCHEDULE" --arg id "$SCHEDULE_ID" '
  .[$script] = {
    script: $script,
    frequency: "custom",
    id: $id,
    custom: $schedule
  }
' "$SCHEDULE_JSON" > "$schedule_tmp"
chmod --reference="$SCHEDULE_JSON" "$schedule_tmp" 2>/dev/null || chmod 0600 "$schedule_tmp"
mv "$schedule_tmp" "$SCHEDULE_JSON"

cron_tmp="$CUSTOM_CRON.tmp.$$"
if [ -f "$CUSTOM_CRON" ]; then
  grep -vF "startCustom.php $USER_SCRIPT_PATH " "$CUSTOM_CRON" > "$cron_tmp" || true
else
  printf '# Generated cron schedule for user.scripts\n' > "$cron_tmp"
fi
printf '%s /usr/local/emhttp/plugins/user.scripts/startCustom.php %s > /dev/null 2>&1\n' \
  "$SCHEDULE" "$USER_SCRIPT_PATH" >> "$cron_tmp"
chmod 0600 "$cron_tmp"
mv "$cron_tmp" "$CUSTOM_CRON"

if [ "$UPDATE_CRON" = 1 ] && command -v update_cron >/dev/null 2>&1; then
  update_cron
fi

printf 'audit=%s\nconfig=%s\nwrapper=%s\nschedule=%s\nbackup=%s\nplugin=%s\npackage_sha256=%s\n' \
  "$AUDIT_INSTALL_PATH" "$AUDIT_CONFIG" "$USER_SCRIPT_PATH" "$SCHEDULE" "$backup_dir" \
  "$plugin_version" "$package_hash"

if [ "$RUN_AUDIT" = 1 ]; then
  "$AUDIT_INSTALL_PATH"
fi
