#!/usr/bin/env bash
set -euo pipefail

bundle_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
destdir="${DESTDIR:-}"
prefix="${PREFIX:-/opt/ci-runner-farm}"
config_dir="${CRF_CONFIG_DIR:-/etc/ci-runner-farm}"
unit_dir="${SYSTEMD_UNIT_DIR:-/etc/systemd/system}"
doc_dir="${CRF_DOC_DIR:-/usr/share/doc/ci-runner-farm-distributed}"
service_user="${CRF_USER:-ci-runner-farm}"
service_group="${CRF_GROUP:-ci-runner-farm}"

rooted() { printf "%s%s" "$destdir" "$1"; }

if [[ -z "$destdir" && "$(id -u)" -ne 0 ]]; then
  echo "install.sh must run as root unless DESTDIR is set" >&2
  exit 1
fi

# BUILD-INFO contains shell-safe values generated by the bundle builder.
# shellcheck disable=SC1091
source "$bundle_root/BUILD-INFO"
[[ "$GIT_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo "BUILD-INFO contains an invalid Git SHA" >&2; exit 1; }
release_id="${VERSION}-${PLATFORM}-${GIT_SHA}"
release_root="$(rooted "$prefix/releases/$release_id")"
current_link="$(rooted "$prefix/current")"

if [[ -z "$destdir" ]]; then
  if ! getent group "$service_group" >/dev/null 2>&1; then
    groupadd --system "$service_group"
  fi
  if ! id "$service_user" >/dev/null 2>&1; then
    useradd --system --gid "$service_group" --home-dir /var/lib/ci-runner-farm --shell /usr/sbin/nologin "$service_user"
  fi
fi

install -d -m 0755 "$(rooted "$prefix/releases")"
if [[ ! -d "$release_root" ]]; then
  tmp_release="${release_root}.installing.$$"
  rm -rf "$tmp_release"
  install -d -m 0755 "$tmp_release"
  cp -a "$bundle_root/bin" "$tmp_release/bin"
  cp -a "$bundle_root/controller" "$tmp_release/controller"
  install -m 0644 "$bundle_root/BUILD-INFO" "$tmp_release/BUILD-INFO"
  mv "$tmp_release" "$release_root"
fi

install -d -m 0755 "$(dirname "$current_link")"
new_link="${current_link}.new.$$"
rm -f "$new_link"
ln -s "releases/$release_id" "$new_link"
mv -Tf "$new_link" "$current_link"

install -d -m 0755 "$(rooted "$unit_dir")"
install -m 0644 "$bundle_root/systemd/ci-runner-farm-controller.service" "$(rooted "$unit_dir/ci-runner-farm-controller.service")"
install -m 0644 "$bundle_root/systemd/ci-runner-farm-node.service" "$(rooted "$unit_dir/ci-runner-farm-node.service")"

install -d -m 0755 "$(rooted "$doc_dir/examples")"
install -m 0644 "$bundle_root/examples/controller-config.example.json" "$(rooted "$doc_dir/examples/controller-config.example.json")"
install -m 0644 "$bundle_root/examples/node-env.example" "$(rooted "$doc_dir/examples/node-env.example")"
install -m 0644 "$bundle_root/examples/runner-manifest.example.json" "$(rooted "$doc_dir/examples/runner-manifest.example.json")"
install -m 0644 "$bundle_root/README.md" "$(rooted "$doc_dir/README.md")"

install -d -m 0750 "$(rooted "$config_dir")"
if [[ -z "$destdir" ]]; then
  chown root:"$service_group" "$(rooted "$config_dir")"
  systemctl daemon-reload
fi

cat <<EOF
Installed CI Runner Farm distributed bundle: $release_id
Current release: $prefix/current

No service was enabled or started.
Copy and secure the examples from $doc_dir/examples into $config_dir,
then explicitly enable the controller and/or node service when ready.
EOF
